scrunch = require('coffee-scrunch')

options =
  input:  './source/js/init.coffee'
  output: './app/assets/js/scripts.js'

task 'build', ->
  scrunch(options)
  .then -> console.log 'finished'
  .end()


