// Generated by CoffeeScript 1.6.2
var cmd, exec;

exec = require('child_process').exec;

option('-w', '--watch', 'Watch the folder');

cmd = function(name, args, options) {
  if (options.watch) {
    name += ' --watch';
  }
  return name + ' ' + args;
};

task('build', 'Build project to ./bin', function(opts) {
  var command;

  command = cmd('coffee', '--compile --output ./bin ./src', opts);
  return exec(command, function(err, stdout, stderr) {
    if (err) {
      throw err;
    }
    return console.log(stdout + stderr);
  });
});

task('build_app', 'Build project to ./bin', function(opts) {
  var command;

  command = cmd('coffee', '--compile --output ./app/js ./app/src', opts);
  console.log(command);
  return exec(command, function(err, stdout, stderr) {
    if (err) {
      throw err;
    }
    return console.log(stdout + stderr);
  });
});

task('mocha', 'Test project using files in ./test', function() {
  return exec('mocha --compilers coffee:coffee-script --timeout 10000 tests', function(err, stdout, stderr) {
    if (err) {
      throw err;
    }
    return console.log(stdout + stderr);
  });
});
