fs = require 'fs'
Scrunch = require 'coffee-scrunch'

input = './source/js/init.coffee'
output = './app/assets/js/scripts.js'

scrunch = new Scrunch
  path: input
  compile: true
  watch: true

scrunch.vent.on 'init', ->
  scrunch.scrunch()

scrunch.vent.on 'scrunch', (data) ->
  console.log '...writing'
  fs.writeFile output, data

task 'dev', ->
  scrunch.init()


