// Generated by CoffeeScript 1.6.1
(function() {
  var $;

  $ = (function() {

    function $(query) {
      return document.querySelector(query);
    }

    $.find = function(parent, query) {
      return parent.querySelector(query);
    };

    $.findAll = function(parent, query) {
      return parent.querySelectorAll(query);
    };

    $.create = function(tag) {
      return document.createElement(tag);
    };

    $.append = function(el) {
      return document.body.appendChild(el);
    };

    $.prepend = function(el) {
      return document.body.insertBefore(el, document.body.firstChild);
    };

    $["class"] = function(className) {
      return document.getElementsByClassName(className);
    };

    $.all = function(query) {
      return document.querySelectorAll(query);
    };

    $.addClass = function(el, className) {
      return el.classList.add(className);
    };

    $.removeClass = function(el, className) {
      return el.classList.remove(className);
    };

    $.toggleClass = function(el, className, value) {
      return el.classList.toggle(className, value);
    };

    $.hasClass = function(el, className) {
      return el.classList.contains(className);
    };

    $.css = function(el, prop, val) {
      return el.style[prop] = val;
    };

    return $;

  })();

  module.exports = $;

}).call(this);
