// Generated by CoffeeScript 1.6.3
(function() {
  var $, app, win;

  $ = require('jqueryify');

  global.document = document;

  global.$ = $;

  app = require('./js/app');

  app.init();

  win = require('nw.gui').Window.get();

  $(document).on('keydown', function(e) {
    switch (e.keyCode) {
      case 82:
        if (e.ctrlKey) {
          return win.reloadDev();
        }
        break;
      case 68:
        if (e.ctrlKey) {
          return win.showDevTools();
        }
    }
  });

}).call(this);
