// Generated by CoffeeScript 1.6.1
(function() {
  var $, Core, Methods, Player, Playlist, core;

  global.document = document;

  Player = require('./js/player');

  Playlist = require('./js/playlist');

  $ = require('./js/dom');

  Core = require('./../bin/core');

  Methods = require('./../bin/methods');

  core = new Core();

  global.App = new Methods(core);

  core.init();

  global.Player = new Player($('.audio-controls'));

  window.playlist = new Playlist($('.playlist'));

}).call(this);
