// Generated by CoffeeScript 1.6.1
(function() {
  var $, Player,
    _this = this;

  $ = require('./dom');

  Player = (function() {

    Player.prototype.events = {
      audio: {
        'durationchange': 'setDuration',
        'progress': 'showBufferProgress',
        'timeupdate': 'showCurrentProgress'
      },
      dom: {
        'click .prev': 'prev',
        'click .next': 'next',
        'click .play-pause': 'toggle'
      },
      keydown: {
        '32': 'toggle'
      }
    };

    function Player(el) {
      var ev, event, method, str, _ref, _ref1, _ref2,
        _this = this;
      this.el = el;
      this.setDuration = function() {
        return Player.prototype.setDuration.apply(_this, arguments);
      };
      this.setSource = function(url) {
        return Player.prototype.setSource.apply(_this, arguments);
      };
      this.setVolume = function(volume) {
        return Player.prototype.setVolume.apply(_this, arguments);
      };
      this.showCurrentProgress = function() {
        return Player.prototype.showCurrentProgress.apply(_this, arguments);
      };
      this.showBufferProgress = function() {
        return Player.prototype.showBufferProgress.apply(_this, arguments);
      };
      this._percent = function(x) {
        return Player.prototype._percent.apply(_this, arguments);
      };
      this.next = function() {
        return Player.prototype.next.apply(_this, arguments);
      };
      this.prev = function() {
        return Player.prototype.prev.apply(_this, arguments);
      };
      this.toggle = function() {
        return Player.prototype.toggle.apply(_this, arguments);
      };
      this.context = document.createElement('audio');
      this.context.setAttribute('autoplay', true);
      this.context.setAttribute('preload', 'auto');
      this.context.setAttribute('controls', true);
      document.body.appendChild(this.context);
      this.range = {
        track: $.find(this.el, '.track'),
        buffer: $.find(this.el, '.buffer')
      };
      _ref = this.events.audio;
      for (event in _ref) {
        method = _ref[event];
        this.context.addEventListener(event, this[method]);
      }
      _ref1 = this.events.dom;
      for (str in _ref1) {
        method = _ref1[str];
        _ref2 = str.match(/^(\w+) (.+)$/), str = _ref2[0], ev = _ref2[1], el = _ref2[2];
        $.find(this.el, el).addEventListener(ev, this[method]);
      }
      document.addEventListener('keydown', function(e) {
        var keyCode, _ref3;
        _ref3 = _this.events.keydown;
        for (keyCode in _ref3) {
          method = _ref3[keyCode];
          if (e.keyCode.toString() === keyCode) {
            _this[method]();
          }
        }
        return true;
      });
    }

    Player.prototype.toggle = function() {
      if (this.context.paused) {
        return this.context.play();
      } else {
        return this.context.pause();
      }
    };

    Player.prototype.prev = function() {
      return this.context.currentTime = 0;
    };

    Player.prototype.next = function() {
      return this.context.currentTime += 10;
    };

    Player.prototype._percent = function(x) {
      return x / this.duration * 100;
    };

    Player.prototype.showBufferProgress = function() {
      var percent;
      if (this.context.buffered.length > 0) {
        percent = this._percent(this.context.buffered.end(0));
        return this.range.buffer.style.width = percent + '%';
      }
    };

    Player.prototype.showCurrentProgress = function() {
      var percent;
      percent = this._percent(this.context.currentTime);
      return this.range.track.style.width = percent + '%';
    };

    Player.prototype.setVolume = function(volume) {
      return this.context.volume = volume;
    };

    Player.prototype.setSource = function(url) {
      return this.context.src = url;
    };

    Player.prototype.setDuration = function() {
      console.log('> Setting duration');
      return this.duration = this.context.duration;
    };

    return Player;

  })();

  module.exports = Player;

}).call(this);
