// Generated by CoffeeScript 1.6.2
(function() {
  var $, Playlist,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = require('./dom');

  Playlist = (function() {
    Playlist.prototype.elements = {
      'input': '.search',
      'table': 'table tbody'
    };

    Playlist.prototype.events = {
      'keydown .search': 'search',
      'click table': 'play'
    };

    function Playlist(el) {
      var ev, method, name, query, str, _ref, _ref1, _ref2;

      this.el = el;
      this.display = __bind(this.display, this);
      this.search = __bind(this.search, this);
      _ref = this.elements;
      for (name in _ref) {
        query = _ref[name];
        this[name] = $.find(this.el, query);
      }
      _ref1 = this.events;
      for (str in _ref1) {
        method = _ref1[str];
        _ref2 = str.match(/^(\w+) (.+)$/), str = _ref2[0], ev = _ref2[1], el = _ref2[2];
        $.find(this.el, el).addEventListener(ev, this[method]);
      }
    }

    Playlist.prototype.search = function(e) {
      var query,
        _this = this;

      if (e.which !== 13) {
        return true;
      }
      query = this.input.value;
      App.getSearchResults(query, 'Songs').then(function(response) {
        return _this.display(response.result);
      });
      App.getSearchResults(query, ['Songs', 'Artists', 'Albums']).then(function(response) {
        return console.log(response);
      });
      return true;
    };

    Playlist.prototype.display = function(songs) {
      var html, i, song, _i, _len;

      html = '';
      for (i = _i = 0, _len = songs.length; _i < _len; i = ++_i) {
        song = songs[i];
        if (i > 10) {
          break;
        }
        html += "<tr data-id=\"" + song.SongID + "\">\n  <td>" + song.SongName + "</td>\n  <td>" + song.ArtistName + "</td>\n  <td>" + song.AlbumName + "</td>\n</tr>";
      }
      return this.table.innerHTML = html;
    };

    Playlist.prototype.play = function(e) {
      var tr;

      tr = e.srcElement.parentNode;
      return Player.setSource("http://localhost:8080/song/" + tr.dataset.id + ".mp3");
    };

    return Playlist;

  })();

  module.exports = Playlist;

}).call(this);
